// СОБРАНО — стартовый каталог. Загружается в data/store.json при первой инициализации.
// После этого правится только через админку (PATCH /api/admin/catalog/*) и в этот файл уже не возвращается.
// Этот файл — источник истины ТОЛЬКО для bootstrap. Для фронта истина — /api/catalog.

module.exports = {
  boxes: [
    { id: "s",  size: "S",  sub: "small",  capacity: 11, price: 1990, order: 1,
      title: "Маленький, но настроенческий",
      desc: "Идеально, чтобы порадовать себя или принести цветы в гости.",
      image: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=900&q=80",
      url: "box.html?size=s", hidden: false },
    { id: "m",  size: "M",  sub: "medium", capacity: 17, price: 2990, order: 2,
      title: "Самый ходовой формат",
      desc: "Достаточно объёма, чтобы стать комплиментом или поводом дня.",
      image: "https://images.unsplash.com/photo-1591886960571-74d43a9d4166?auto=format&fit=crop&w=900&q=80",
      url: "box.html?size=m", hidden: false },
    { id: "l",  size: "L",  sub: "large",  capacity: 25, price: 4490, order: 3,
      title: "Заметный жест",
      desc: "Когда хочется, чтобы цветы говорили громче слов.",
      image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=900&q=80",
      url: "box.html?size=l", hidden: false },
    { id: "xl", size: "XL", sub: "extra",  capacity: 35, price: 5990, order: 4,
      title: "Праздник без оговорок",
      desc: "День рождения, юбилей, годовщина — повод найдётся.",
      image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=900&q=80",
      url: "box.html?size=xl", hidden: false },
  ],

  flowers: [
    { id: "peony-sara",     name: "Пион «Сара Бернар»",     cat: "peony",    priceFrom: 320, image: "https://images.unsplash.com/photo-1591886960571-74d43a9d4166?auto=format&fit=crop&w=700&q=80", meta: "Душистый · 60 см · бутон 8 см",      stock: true,  tag: "fresh", sale: false, hidden: false, order: 1 },
    { id: "peony-duchess",  name: "Пион «Дюшес»",            cat: "peony",    priceFrom: 280, image: "https://images.unsplash.com/photo-1495231916356-a86217efff12?auto=format&fit=crop&w=700&q=80", meta: "Белый · 55 см · кустовой",            stock: true,  tag: "fresh", sale: true,  hidden: false, order: 2 },
    { id: "rose-yumilia",   name: "Роза «Юмилия»",           cat: "rose",     priceFrom: 240, image: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=700&q=80", meta: "Кремовая · 50 см · 5 бутонов",        stock: true,  tag: "fresh", sale: false, hidden: false, order: 3 },
    { id: "rose-ecuador",   name: "Роза «Эквадор»",          cat: "rose",     priceFrom: 290, image: "https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=700&q=80", meta: "Красная · 70 см · крупная",          stock: true,  tag: "fresh", sale: false, hidden: false, order: 4 },
    { id: "rose-austin",    name: "Роза «Дэвид Остин»",      cat: "rose",     priceFrom: 380, image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=700&q=80", meta: "Пионовидная · 45 см",                stock: true,  tag: "exo",   sale: false, hidden: false, order: 5 },
    { id: "tulip-french",   name: "Тюльпан Французский",     cat: "seasonal", priceFrom: 180, image: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=700&q=80", meta: "Бордовый · пионовидный · 55 см",     stock: true,  tag: "fresh", sale: false, hidden: false, order: 6 },
    { id: "eustoma-rosita", name: "Эустома «Розита»",        cat: "seasonal", priceFrom: 210, image: "https://images.unsplash.com/photo-1530092285049-1c42085fd395?auto=format&fit=crop&w=700&q=80", meta: "Белая · кустовая · 45 см",            stock: true,  tag: "fresh", sale: false, hidden: false, order: 7 },
    { id: "gypsophila",     name: "Гипсофила «Облако»",      cat: "seasonal", priceFrom: 140, image: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=700&q=80", meta: "Воздушная · 50 см",                  stock: true,  tag: "season",sale: false, hidden: false, order: 8 },
    { id: "ranunculus",     name: "Ранункулюс",              cat: "seasonal", priceFrom: 260, image: "https://images.unsplash.com/photo-1469259943454-aa100abba749?auto=format&fit=crop&w=700&q=80", meta: "Персиковый · 35 см",                 stock: true,  tag: "fresh", sale: false, hidden: false, order: 9 },
    { id: "hortensia",      name: "Гортензия",               cat: "seasonal", priceFrom: 340, image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=700&q=80", meta: "Голубая · 55 см · крупная шапка",     stock: false, tag: "out",   sale: false, hidden: false, order: 10 },
    { id: "anthurium",      name: "Антуриум «Тропик»",       cat: "exo",      priceFrom: 360, image: "https://images.unsplash.com/photo-1502977249166-824b3a8a4d6d?auto=format&fit=crop&w=700&q=80", meta: "Бордовый · глянец · 45 см",          stock: true,  tag: "exo",   sale: false, hidden: false, order: 11 },
    { id: "protea",         name: "Протея «Кинг»",           cat: "exo",      priceFrom: 520, image: "https://images.unsplash.com/photo-1483794344563-d27a8d18014e?auto=format&fit=crop&w=700&q=80", meta: "Розовая · 40 см · артишок",          stock: true,  tag: "exo",   sale: false, hidden: false, order: 12 },
    { id: "cotton",         name: "Хлопок натуральный",      cat: "dry",      priceFrom: 180, image: "https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=700&q=80", meta: "Сухоцвет · 40 см · 3 коробочки",     stock: true,  tag: "dry",   sale: false, hidden: false, order: 13 },
    { id: "lagurus",        name: "Лагурус «Заячий хвост»",  cat: "dry",      priceFrom: 120, image: "https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=700&q=80", meta: "Сухоцвет · 35 см · бежевый",         stock: true,  tag: "dry",   sale: false, hidden: false, order: 14 },
    { id: "pampas",         name: "Пампасная трава",         cat: "dry",      priceFrom: 240, image: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=700&q=80", meta: "Сухоцвет · 80 см",                   stock: false, tag: "out",   sale: false, hidden: false, order: 15 },
    { id: "eucalyptus",     name: "Эвкалипт «Цинерея»",      cat: "green",    priceFrom: 140, image: "https://images.unsplash.com/photo-1483794344563-d27a8d18014e?auto=format&fit=crop&w=700&q=80", meta: "Зелень · 50 см · ароматная",         stock: true,  tag: "fresh", sale: false, hidden: false, order: 16 },
  ],

  picks: [
    { id: "morning-light",   cat: "home",    title: "Утренний свет",          price: 3490, oldPrice: null, order: 1, hidden: false,
      desc: "Спокойный микс эустомы, белой розы и лагуруса. Ваза в подарок.",
      image: "https://images.unsplash.com/photo-1509223197845-458d87318791?auto=format&fit=crop&w=900&q=80",
      boxId: "m", flowers: { "eustoma-rosita": 7, "rose-yumilia": 6, "lagurus": 4 }, addons: ["vase"] },
    { id: "gift-day",        cat: "gift",    title: "День, который запомнят", price: 5290, oldPrice: 5870, order: 2, hidden: false,
      desc: "Тёплый микс из пионов «Сара Бернар», кустовых роз «Юмилия» и облака гипсофилы. С открыткой ручной работы и подкормкой.",
      image: "https://images.unsplash.com/photo-1502977249166-824b3a8a4d6d?auto=format&fit=crop&w=1200&q=80",
      boxId: "l", flowers: { "peony-sara": 8, "rose-yumilia": 10, "gypsophila": 5, "ranunculus": 2 }, addons: ["card", "feed"] },
    { id: "velvet-evening",  cat: "exo",     title: "Бархатный вечер",        price: 6590, oldPrice: null, order: 3, hidden: false,
      desc: "Бордовые тюльпаны, антуриум, сухоцветы и хлопок. Драматично.",
      image: "https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=900&q=80",
      boxId: "xl", flowers: { "tulip-french": 12, "anthurium": 6, "cotton": 8, "lagurus": 9 }, addons: [] },
    { id: "sunday-coffee",   cat: "home",    title: "Воскресный кофе",        price: 2190, oldPrice: null, order: 4, hidden: false,
      desc: "Скромный микс пионов и кустовой розы. Идеально для маленьких ваз и кухонных столов.",
      image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=900&q=80",
      boxId: "s", flowers: { "peony-duchess": 5, "rose-yumilia": 4, "eucalyptus": 2 }, addons: [] },
    { id: "desk-stand",      cat: "home",    title: "Рабочий стол",           price: 2590, oldPrice: null, order: 5, hidden: false,
      desc: "Сухоцветы и хлопок. Стоит месяцами, не требует ухода — ставите и забываете.",
      image: "https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=900&q=80",
      boxId: "s", flowers: { "cotton": 5, "lagurus": 4, "eucalyptus": 2 }, addons: ["vase"] },
    { id: "thanks-for-being",cat: "gift",    title: "Спасибо, что есть",      price: 3990, oldPrice: null, order: 6, hidden: false,
      desc: "Персиковые ранункулюсы, белые пионы, эустома. Универсальный «вне-повода» подарок.",
      image: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=900&q=80",
      boxId: "m", flowers: { "ranunculus": 8, "peony-duchess": 5, "eustoma-rosita": 4 }, addons: ["card"] },
    { id: "warm-message",    cat: "gift",    title: "Тёплое сообщение",       price: 3690, oldPrice: null, order: 7, hidden: false,
      desc: "Нейтральная палитра в кремовых и пыльно-розовых тонах. Подходит на любой возраст.",
      image: "https://images.unsplash.com/photo-1591886960571-74d43a9d4166?auto=format&fit=crop&w=900&q=80",
      boxId: "m", flowers: { "rose-yumilia": 6, "eustoma-rosita": 6, "cotton": 5 }, addons: ["card"] },
    { id: "wild-heart",      cat: "exo",     title: "Дикое сердце",           price: 5990, oldPrice: null, order: 8, hidden: false,
      desc: "Протея и антуриум — букет с характером. Не для всех, но если зайдёт — навсегда.",
      image: "https://images.unsplash.com/photo-1530092285049-1c42085fd395?auto=format&fit=crop&w=900&q=80",
      boxId: "l", flowers: { "protea": 3, "anthurium": 6, "eucalyptus": 10, "cotton": 6 }, addons: [] },
    { id: "first-date",      cat: "romance", title: "Первое свидание",        price: 2290, oldPrice: null, order: 9, hidden: false,
      desc: "Маленький, но очень нежный набор: пастельные тона, без излишеств.",
      image: "https://images.unsplash.com/photo-1495231916356-a86217efff12?auto=format&fit=crop&w=900&q=80",
      boxId: "s", flowers: { "peony-sara": 4, "rose-yumilia": 4, "ranunculus": 3 }, addons: [] },
    { id: "ten-years",       cat: "anniv",   title: "Десять лет вместе",      price: 7290, oldPrice: null, order: 10, hidden: false,
      desc: "Большой объём в красно-винных тонах. Эквадорские розы, антуриум, бордовый тюльпан.",
      image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=900&q=80",
      boxId: "xl", flowers: { "rose-ecuador": 15, "tulip-french": 8, "anthurium": 6, "eucalyptus": 6 }, addons: ["card"] },
  ],

  addons: [
    { id: "vase",   title: "Классическая ваза",     price: 690, image: "https://images.unsplash.com/photo-1490312278390-ab64016e0aa9?auto=format&fit=crop&w=800&q=80", placeholder: null,  hidden: false, order: 1, desc: "Прозрачное стекло, высота 24 см. Подходит к любому из боксов." },
    { id: "green",  title: "Декоративная зелень",   price: 290, image: "https://images.unsplash.com/photo-1483794344563-d27a8d18014e?auto=format&fit=crop&w=800&q=80", placeholder: null,  hidden: false, order: 2, desc: "Декоративная зелень — для объёма и фактуры." },
    { id: "feed",   title: "Подкормка для цветов",  price:  90, image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=800&q=80", placeholder: null,  hidden: false, order: 3, desc: "Пакетик подкормки. Продлевает жизнь букета на 3–5 дней." },
    { id: "card",   title: "Открытка ручной работы",price: 190, image: null,                                                                                            placeholder: "⊹",   hidden: false, order: 4, desc: "Бумага хлопок, конверт крафт. Подпись пишем от руки." },
    { id: "ribbon", title: "Бант атласный",         price: 150, image: null,                                                                                            placeholder: "ﾐ", hidden: false, order: 5, desc: "Атласная лента, цвет под состав букета." },
  ],

  promos: [
    { code: "BLOOM10", discountPct: 10, label: "BLOOM10", expiresAt: null, maxUses: null, usedCount: 0, minSubtotal: 0, active: true },
    { code: "LOVE15",  discountPct: 15, label: "LOVE15",  expiresAt: null, maxUses: null, usedCount: 0, minSubtotal: 0, active: true },
  ],

  // Способы оплаты на чекауте. Два built-in метода через Robokassa — их нельзя удалить, можно отключить флагом `active`.
  // Custom-методы (перевод на карту, наличные курьеру, безнал по счёту и т.п.) админ добавляет сам — для них работает поле `instruction`,
  // которое показывается клиенту на thank-you.
  payments: [
    { id: "robokassa-card", type: "robokassa-card", title: "Карта онлайн",
      description: "Visa, Mastercard, Mir — через защищённый шлюз Robokassa, 3-D Secure.",
      icon: "CARD", instruction: "", active: true, order: 1, builtin: true, hidden: false },
    { id: "robokassa-sbp",  type: "robokassa-sbp",  title: "СБП — Система быстрых платежей",
      description: "QR-код в приложении банка. Без комиссии.",
      icon: "СБП", instruction: "", active: true, order: 2, builtin: true, hidden: false },
  ],

  delivery: {
    own:    { id: "own",    label: "Своя доставка", price: 500, eta: "в выбранный интервал" },
    yandex: { id: "yandex", label: "Яндекс Go",     price: 0,   eta: "от 60 минут · по тарифу" },
  },
};
